### ISSUE TITLE
ValueError: Cannot create group in read only mode.

### ISSUE THREAD

**Issue by kikyo1314** [krasserm/super-resolution#13]
when i try to load the trained model using demo.py, there is an error

```
Traceback (most recent call last):
  File "F:/zhangqianqian/super-resolution-master/demo.py", line 78, in <module>
    main(args)
  File "F:/zhangqianqian/super-resolution-master/demo.py", line 48, in main
    model = load_model(args.model)
  File "F:\super-resolution-master\model\__init__.py", line 7, in load_model
    return train._load_model(path)
  File "F:\super-resolution-master\train.py", line 76, in _load_model
    return load_model(path, custom_objects={**_custom_objects, **_custom_objects_backwards_compat})
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 221, in _deserialize_model
    model_config = f['model_config']
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.
```

**Comment by krasserm** [comment]
What is the Keras version and which model are you trying to load?

**Comment by kikyo1314** [comment]
Thanks for your reply, and the Keras versiom is 2.2.4, the model  trained using the train.py and my own dataset. For example:epoch-137-psnr-67.9107.h5, i changed the defination of parser.add_argument('-m', '--model', default=2,
                        help='model file') to  parser.add_argument('-m', '--model', default="./models/epoch-137-psnr-67.0595.h5",help='model file') in demo.py, and then there would be the error :ValueError: Cannot create group in read only mode. i don't know why

**Comment by krasserm** [comment]
Have you made any changes to the source code? If yes, please send a complete diff.

**Comment by kikyo1314** [comment]
Thanks very much, I know the reason, it just because i chage the ModelCheckpointAfter, so it just save the weights.

**Comment by krasserm** [comment]
I suspected something like that, great you found the reason.

**Comment by Mahibro** [comment]
@kikyo1314 How did you resolve the issue?what is the reason?why it is not loading(am using resnet pretrained model) Where did you change checkpoint?

**Comment by angyee** [comment]
i am running

sudo python3 keras_to_tensorflow.py --input_model=/home/deepedge/mask_rcnn-master/mask_rcnn_damage_0010.h5 --output_model=/home/deepedge/mask_rcnn-master/dent.pb

and getting error

Using TensorFlow backend.
E0619 15:22:44.379571 140399717234496 keras_to_tensorflow.py:95] Input file specified only holds the weights, and not the model definition. Save the model using model.save(filename.h5) which will contain the network architecture as well as its weights. If the model is saved using the model.save_weights(filename) function, either input_model_json or input_model_yaml flags should be set to to import the network architecture prior to loading the weights.
Check the keras documentation for more details (https://keras.io/getting-started/faq/)
Traceback (most recent call last):
File "keras_to_tensorflow.py", line 182, in
app.run(main)
File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
_run_main(main, args)
File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
sys.exit(main(argv))
File "keras_to_tensorflow.py", line 128, in main
model = load_model(FLAGS.input_model, FLAGS.input_model_json, FLAGS.input_model_yaml)
File "keras_to_tensorflow.py", line 106, in load_model
raise wrong_file_err
File "keras_to_tensorflow.py", line 63, in load_model
model = keras.models.load_model(input_model_path)
File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 419, in load_model
model = _deserialize_model(f, custom_objects, compile)
File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 221, in _deserialize_model
model_config = f['model_config']
File "/usr/local/lib/python3.6/dist-packages/keras/utils/io_utils.py", line 302, in getitem
raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.

@kikyo1314 @krasserm @Mahibro

**Comment by kikyo1314** [comment]
> @kikyo1314 How did you resolve the issue?what is the reason?why it is not loading(am using resnet pretrained model) Where did you change checkpoint?

I changed the' model_checkpoint_after'in 'callback.py ', and it just save the weights only. So when the load_model was used there would be occuring the error.
