### ISSUE TITLE
evaluate.py requires compiled model

### ISSUE THREAD

**Issue by ink1** [krasserm/super-resolution#20]
Hi Martin,
Thanks again for sharing your code. I'm working with a custom dataset and following your guidelines on training SRGAN with EDSR baseline model. Leaving the results aside, things appear to be working and therefore I tried doing evaluation using evaluate.py but it gives me this error
```
INFO: Evaluate model ./tmp/generator-epoch-001.h5
Traceback (most recent call last):
  File "evaluate.py", line 104, in <module>
    main(parser().parse_args())
  File "evaluate.py", line 60, in main
    psnr = evaluate_model(mp, generator)
  File "evaluate.py", line 39, in evaluate_model
    return model.evaluate_generator(generator, steps=100, verbose=1)[1]
  File "/home/miniconda2/envs/py36tfsr-cpu/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/miniconda2/envs/py36tfsr-cpu/lib/python3.6/site-packages/keras/engine/training.py", line 1472, in evaluate_generator
    verbose=verbose)
  File "/home/miniconda2/envs/py36tfsr-cpu/lib/python3.6/site-packages/keras/engine/training_generator.py", line 275, in evaluate_generator
    model._make_test_function()
  File "/home/miniconda2/envs/py36tfsr-cpu/lib/python3.6/site-packages/keras/engine/training.py", line 523, in _make_test_function
    raise RuntimeError('You must compile your model before using it.')
RuntimeError: You must compile your model before using it.
```
Evaluation on WDSR models works fine (I patched the code to do a custom range of input indices and can do a PR if you want). Demo using EDSR models works fine too. Why does Keras complain about EDSR models and not about WDSR?

**Comment by ink1** [comment]
Might be Keras or TF related?
```
keras==2.2.4
tensorflow==1.13.1
```

**Comment by ink1** [comment]
A quick fix for me was to add compile with the options used in train.py
```
def evaluate_model(model_path, generator):
    """Evaluate model against DIV2K validation set and return PSNR"""
    logger.info('Load model %s', model_path)
    model = load_model(model_path)
    model.compile(optimizer=Adam(lr=0.00001), loss=mean_absolute_error, metrics=[psnr])
    logger.info('Evaluate model %s', model_path)
    return model.evaluate_generator(generator, steps=100, verbose=1)[1]
```
plus, of course, all the dependencies.
