### ISSUE TITLE
load_model error in demo.py

### ISSUE THREAD

**Issue by aligoglos** [krasserm/super-resolution#27]
I tried run `demo.py` with [this model](https://drive.google.com/file/d/1ZTIz1YVXFTI2z3rvBfVuBSthJLJZivxC/view) but this error occurred :

```
D:\Artificial Intelligence\SuperResolution\Images\wdsr>python demo.py
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0817 19:36:48.204280  8632 deprecation_wrapper.py:119] From D:\Artificial Intelligence\SuperResolution\Images\wdsr\util.py:30: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0817 19:36:48.204280  8632 deprecation_wrapper.py:119] From D:\Artificial Intelligence\SuperResolution\Images\wdsr\util.py:33: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-08-17 19:36:48.228737: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-08-17 19:36:48.238670: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-08-17 19:36:48.860316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
2019-08-17 19:36:48.868030: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-08-17 19:36:48.874822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-17 19:36:50.439236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-17 19:36:50.445774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2019-08-17 19:36:50.448722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2019-08-17 19:36:50.453298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3276 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Began Load Image
W0817 19:36:50.487827  8632 deprecation_wrapper.py:119] From C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Traceback (most recent call last):
  File "demo.py", line 73, in <module>
    main(args)
  File "demo.py", line 41, in main
    model = load_model(args.model)
  File "D:\Artificial Intelligence\SuperResolution\Images\wdsr\model\__init__.py", line 7, in load_model
    return train._load_model(path)
  File "D:\Artificial Intelligence\SuperResolution\Images\wdsr\train.py", line 76, in _load_model
    return load_model(path, custom_objects={**_custom_objects, **_custom_objects_backwards_compat})
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\layers\core.py", line 687, in call
    return self.function(inputs, **arguments)
  File "/home/martin/Development/extern/wdsr/model/common.py", line 14, in <lambda>
IndexError: tuple index out of range
```

**Comment by krasserm** [comment]
I wasn't able to reproduce the error you reported i.e. `demo.py` runs as described in my environment.

- have you created a conda environment with `conda env create -f environment-gpu.yml` as described in the docs? It doesn't seem so as you're running under Python 3.5 whereas environment-gpu.yml has Python 3.6 as dependency (which is required anyway as the code uses Python 3.6 features).
- what Keras version are you using?

**Comment by aligoglos** [comment]
I didn't use `conda ` I tried run your code in python 3.5 so I changes al  f string formats.
and my keras version is 2.2.4

**Comment by krasserm** [comment]
The Keras version should be fine but since I don't know any details of the environment you're running the code it's hard to say what causes this error. Can you please try re-running in the conda environment and see if the error persists?

**Comment by krasserm** [comment]
Please re-open if the error persists with the supported conda environment.
