### ISSUE TITLE
train custom datasets error

### ISSUE THREAD

**Issue by phexic** [krasserm/super-resolution#5]
Thank you for doing a great job firstly. 
I organized my dataset according to the format of DIV2K, when i trained the model with `python train.py --dataset ./DIV2K_BIN --outdir ./output --profile wdsr-a-32 --scale 2`, the following error occurs: 
```
Epoch 00001: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Traceback (most recent call last):
  File "train.py", line 395, in <module>
    main(args)
  File "train.py", line 182, in main
    callbacks=callbacks)
  File "/data1/wangguozhi/anaconda3/envs/sisr/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/data1/wangguozhi/anaconda3/envs/sisr/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/data1/wangguozhi/anaconda3/envs/sisr/lib/python3.6/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/data1/wangguozhi/anaconda3/envs/sisr/lib/python3.6/site-packages/keras/utils/data_utils.py", line 601, in get
    six.reraise(*sys.exc_info())
  File "/data1/wangguozhi/anaconda3/envs/sisr/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/data1/wangguozhi/anaconda3/envs/sisr/lib/python3.6/site-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/data1/wangguozhi/anaconda3/envs/sisr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/data1/wangguozhi/anaconda3/envs/sisr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data1/wangguozhi/anaconda3/envs/sisr/lib/python3.6/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/data1/wangguozhi/algrithm/super-resolution/data.py", line 75, in __getitem__
    return self._batch_n(self.image_ids[beg:end])
  File "/data1/wangguozhi/algrithm/super-resolution/data.py", line 96, in _batch_n
    hr_batch[i] = hr
ValueError: could not broadcast input array from shape (96,9,3) into shape (96,96,3)
```
could you offer me some suggestions?

**Comment by krasserm** [comment]
I just tried with a clean checkout from Github, converting the DIV2K data and running the training command you provided but cannot reproduce the problem. I'm a bit surprised by `could not broadcast input array from shape (96,9,3) into shape (96,96,3)`. Have you by accident made any changes to the sources? If not, please check again the structure of your DIV2K and DIV2K_BIN directories.

**Comment by phexic** [comment]
I rearranged the dataset according to the DIV2K standard and trained it with commands. I am currently able to train successfully, thank you very much for your tips. I will continue to check the error of the previous datasets.

**Comment by krasserm** [comment]
Glad it works now. I just created #6 that should make DIV2K downloads easier.

**Comment by PIjarihd** [comment]
@krasserm @phexic How should I prepare the data for custom data training? What pre-processing do I need? Can you explain stepwise or can you provide some link with the instruction?
